# Generated by Django 3.2.13 on 2022-10-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%M/%d'),
        ),
    ]
